name: Azure Static Web Apps CI/CD - Integrated

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      # 管理画面のビルド
      - name: Build Admin Dashboard
        run: |
          cd admin-dashboard
          npm ci
          npm run build
          cd ..
          rm -rf admin/*
          cp -r admin-dashboard/build/* admin/
        env:
          REACT_APP_API_URL: /api
          REACT_APP_ENVIRONMENT: production
          CI: false
          ESLINT_NO_DEV_ERRORS: true
          GENERATE_SOURCEMAP: false
      
      # デプロイ専用ディレクトリを作成
      - name: Create deployment directory
        run: |
          mkdir -p deploy
          # 必要なファイルのみをコピー
          cp index.html deploy/
          cp -r admin deploy/
          cp -r css deploy/
          cp -r js deploy/
          cp -r images deploy/
          cp staticwebapp.config.json deploy/
          cp test-api-manual.html deploy/ || true
          cp debug-api.html deploy/ || true
          cp favicon.ico deploy/ || true
          cp manifest.json deploy/ || true
          cp robots.txt deploy/ || true
          # サイズチェック
          du -sh deploy/
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_FLOWER_0F6517B00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "deploy" # デプロイ専用ディレクトリを指定
          api_location: "api" # Azure Functions API ディレクトリを指定
          output_location: "" # Built app content directory - optional
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_FLOWER_0F6517B00 }}
          action: "close"