name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && github.event.action == 'opened' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Claude PR Action
        uses: grll/claude-code-action@beta
        with:
          use_oauth: true
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          timeout_minutes: "60"
          allowed_tools: "Bash,Read,Write,Edit,MultiEdit,Glob,Grep,LS,Task,TodoRead,TodoWrite,WebFetch,WebSearch,mcp__github__get_issue,mcp__github__create_issue,mcp__github__list_issues,mcp__github__get_pull_request,mcp__github__create_pull_request,mcp__github__list_pull_requests,mcp__github__get_file,mcp__github__create_file,mcp__github__update_file,mcp__github__delete_file,mcp__github__search_repositories,mcp__github__get_repository,mcp__github__list_commits,mcp__github__create_branch,mcp__github__list_branches"


