name: Clear Workflow Cache

on:
  workflow_dispatch:

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        run: |
          echo "Clearing workflow cache..."
          echo "This is a dummy workflow to force GitHub to refresh workflow definitions"